asyncapi: '2.5.0'
info:
  title: Notification Service
  version: 1.0.0
  description: |
    Manages all customer information
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  test:
    url: kafka://localhost:9092
    protocol: kafka-secure
    description: Test brokerd
defaultContentType: application/json
channels:
  customer_changed:
    servers: [ test ]
    publish:
      operationId: updateCustomerInformation
      message:
        $ref: '#/components/messages/CustomerChanged'
  order_created:
    servers: [ test ]
    publish:
      operationId: sendOrderConfirmation
      message:
        $ref: '#/components/messages/OrderCreated'
  order_shipped:
    servers: [ test ]
    publish:
      operationId: sendShippingNotification
      message:
        $ref: '#/components/messages/OrderShipped'
components:
  messages:
    CustomerChanged:
      title: CustomerChangedEvent
      summary: Information about a customer has changed
      payload:
        $ref: '#/components/schemas/Customer'
    OrderCreated:
      title: OrderCreatedEvent
      summary: Sends a confirmation of a new order to the customer
      payload:
        $ref: '#/components/schemas/Order'
    OrderShipped:
      title: OrderShippedEvent
      summary: Sends a shipping notification to the customer
      payload:
        $ref: '#/components/schemas/ShippingInformation'
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
          format: uuid
        customer:
          $ref: '#/components/schemas/Customer'
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
        total:
          type: number
          format: float
    Customer:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string
    Item:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        quantity:
          type: integer
        price:
          type: number
          format: float
    ShippingInformation:
      type: object
      properties:
        id:
          type: string
          format: uuid
        billing_id:
          type: string
          format: uuid
        customer:
          $ref: '#/components/schemas/Customer'
        items:
          type: array
          items:
            $ref: '#/components/schemas/ShippedItem'
        shipping_address:
          type: object
          properties:
            street:
              type: string
            city:
              type: string
            state:
              type: string
            zip:
              type: string
        date:
          type: string
          format: date-time
    ShippedItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        quantity:
          type: integer
    Notification:
      type: object
      properties:
        id:
          type: string
          format: uuid
        customer:
          $ref: '#/components/schemas/Customer'
        type:
          type: string
        message:
          type: string
        date:
          type: string
          format: date